#Makefile for Red Hat Documentation
#Created by Jeff Fearn <jfearn@redhat.com>
#Copyright Red Hat Inc. 2006

XML_LANG	= en-US
DOCNAME		= Weld_Reference_Guide
PRODUCT		= Weld_Beans
BRAND		= JBoss

TRANSLATIONS    = $(XML_LANG)
OTHER_LANGS    = es-ES fr-FR it-IT ja-JP zh-CN ko-KR zh-TW pt-BR de-DE
#TRANSLATIONS   = $(XML_LANG) $(OTHER_LANGS)

COMMON_CONFIG  = /usr/share/publican
include $(COMMON_CONFIG)/make/Makefile.common
