#!/bin/sh
set -eu

# Export translations from zanata to git (eg before a release)

# pull latest translations into po files
echo "Pulling latest translations from Zanata server"
mvn zanata:publican-pull -e

echo "Finished! Don't forget to check src/main/docbook into version control to record the updated PO files"
