[[devmode]]
== Development Mode

Weld comes with a special mode for application development. When enabled, certain built-in tools which facilitate the development of CDI applications, are available.

NOTE: The development mode should not be used in production as it may have negative impact on the performance of the application. Make sure to disable the development mode before deploying to production.

WARNING: Not all environments and containers may support the development mode and all tools. Check the <<devtools,tools>> details and the container documentation.

[[devmode-enable]]
=== How to enable the development mode

Set the Servlet initialization parameter `org.jboss.weld.development` to `true`:

[source.XML, xml]
-----------------------------------------------------------------------------------------------------------
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">

    <context-param>
        <param-name>org.jboss.weld.development</param-name>
        <param-value>true</param-value>
    </context-param>

</web-app>
-----------------------------------------------------------------------------------------------------------

You should see the following log message when deploying your application:

-----------------------------------------------------------------------------------------------------------
=====================================

 Weld Development Mode: ENABLED

=====================================
-----------------------------------------------------------------------------------------------------------

NOTE: An integrator is allowed to specify an alternative way of enabling the development mode.

[[devtools]]
=== Development Tools

[[probe]]
==== Probe

This tool allows to inspect the application CDI components at runtime. See also the http://probe-weld.itos.redhat.com/weld-numberguess/weld-probe[demo application hosted on OpenShift]. Currently, this tool is only available in a web application. JSON data are available through the REST API. However, a default HTML client (single-page application) is also available at `{webappContextPath}/weld-probe`, e.g. `http://localhost:8080/weld-numberguess/weld-probe`.

Right now, the integration is provided for WildFly (unofficial patch), Tomcat and Jetty (Weld Servlet).

TIP: There are some configuration properties which allow to tune or disable Probe features, e.g. to limit the set of components which will be monitored. See also <<config-dev-mode>>.