ifdef::generate-index-link[]
link:index.html[Weld {weldVersion} - CDI Reference Implementation]
endif::[]

[[part-2]]
= Getting Start with Weld, the CDI Reference Implementation

Weld, the CDI Reference Implementation (RI), can be downloaded from the
http://weld.cdi-spec.org/download[download page]. Information about the
Weld source code repository and instructions about how to obtain and
build the source can be found on the same page.

Weld provides a complete SPI allowing Java EE containers such as
WildFly, GlassFish and WebLogic to use Weld as their built-in CDI
implementation. Weld also runs in servlet engines like Tomcat and Jetty,
or even in a plain Java SE environment.

Weld comes with an extensive library of examples, which are a great
starting point from which to learn CDI. In addition, a number of
quickstarts featuring CDI can be found at the
http://www.jboss.org/developer/quickstarts.html[JBoss Developer site]

include::gettingstarted.asciidoc[]

include::weldexamples.asciidoc[]
