[[part-5]]
= Weld Reference Guide

[partintro]
--
Weld is the reference implementation of CDI, and is used by WildFly,
GlassFish and WebLogic to provide CDI services for Java Enterprise
Edition (Java EE) applications. Weld also goes beyond the environments
and APIs defined by the CDI specification by providing support for a
number of other environments (such as a servlet container such as
Tomcat, or Java SE).

You might also want to check out
http://deltaspike.apache.org/[DeltaSpike] project which provides
portable extensions to CDI.

If you want to get started quickly using Weld (and, in turn, CDI) with
WildFly, GlassFish or Tomcat and experiment with one of the examples,
take a look at <<gettingstarted>>. Otherwise read on for a
exhaustive discussion of using Weld in all the environments and application
servers it supports and the Weld extensions.
--

include::environments.asciidoc[]

include::configure.asciidoc[]

include::logging.asciidoc[]

include::developmentmode.asciidoc[]

include::contexts.asciidoc[]

include::ri-spi.asciidoc[]
