/*
 * JBoss, Home of Professional Open Source
 * Copyright 2026, Red Hat, Inc., and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.weld.bean.proxy;

import io.quarkus.gizmo2.ClassOutput;

/**
 * A simple {@link ClassOutput} implementation that captures generated class bytecode in memory.
 * Note: This class assumes only a single class is generated per invocation; otherwise an exception is thrown
 *
 * @author Weld Team
 */
public class ByteArrayClassOutput implements ClassOutput {

    private byte[] bytecode = null;

    @Override
    public void write(String className, byte[] data) {
        if (bytecode == null) {
            this.bytecode = data;
        } else {
            throw new IllegalStateException("Gizmo attempted to create more than one class per proxy created!");
        }
    }

    /**
     * Gets the generated bytecode.
     *
     * @return the bytecode
     */
    public byte[] getBytes() {
        return bytecode;
    }
}
